CREATE TYPE "IncrementCurveType" AS ENUM (
  'LINEAR_TIERED',
  'LOGARITHMIC',
  'EXPONENTIAL',
  'MARKET_SIGMOID'
);

ALTER TABLE "AuctionRoom"
ADD COLUMN "incrementCurve" "IncrementCurveType" NOT NULL DEFAULT 'LINEAR_TIERED',
ADD COLUMN "curveAlphaParam" DOUBLE PRECISION DEFAULT 5.0,
ADD COLUMN "curveGammaParam" DOUBLE PRECISION DEFAULT 0.0015;
